// The renderer seam. The built-in look ("tofu" in the config) is the pixel
// robot 豆腐 — itself a packaged sprite skin generated by
// tools/gen_tofu_skin.py — so the degrade chain is: configured pack → tofu →
// the CSS robot as the last resort nothing-can-404 fallback. Live2D becomes
// another branch here in stage 5; this factory stays the single switch point.

import { mountFallback } from "./skins/fallback.js";
import { mountSprite } from "./skins/sprite.js";

const BUILTIN = "tofu";

export async function createRenderer(mount, avatar, hooks) {
  const wanted = avatar?.renderer === "sprite" && avatar.model_id ? avatar.model_id : BUILTIN;
  try {
    return await mountSprite(mount, wanted, hooks);
  } catch (err) {
    // Missing pack, malformed manifest, oversized sheet: degrade, and say so
    // in the browser console (the panel's log tab shows server-side lines).
    console.warn(`皮肤包 ${wanted} 加载失败，退回内置形象：`, err);
  }
  if (wanted !== BUILTIN) {
    try {
      return await mountSprite(mount, BUILTIN, hooks);
    } catch (err) {
      console.warn("豆腐皮肤也加载失败，退回 CSS 形象：", err);
    }
  }
  return mountFallback(mount, hooks);
}

// Pointer handling shared by every skin: <4px of movement is a poke, more is
// a drag (forwarded to the desktop shell when one is hosting us). Not
// -webkit-app-region: drag — that swallows clicks and the poke dies.
//
// The listeners bind to the long-lived mount element ONCE; a skin remount
// only swaps the hook object. Re-adding listeners per mount would stack
// them, and one click would send a poke per remount ever done.
export function attachPointer(el, hooks) {
  if (el.__petHooks) {
    el.__petHooks.onPoke = hooks.onPoke;
    return;
  }
  el.__petHooks = { onPoke: hooks.onPoke };
  const shell = window.bilisamaShell;
  let start = null;
  let moved = false;

  el.addEventListener("pointerdown", (e) => {
    if (e.button !== 0) return;
    el.setPointerCapture(e.pointerId);
    start = { x: e.screenX, y: e.screenY };
    moved = false;
    shell?.dragStart?.(e.screenX, e.screenY);
  });

  el.addEventListener("pointermove", (e) => {
    if (!start) return;
    if (!moved && Math.hypot(e.screenX - start.x, e.screenY - start.y) >= 4) {
      moved = true;
      el.classList.add("dragging");
    }
    if (moved) shell?.dragMove?.(e.screenX, e.screenY);
  });

  const end = (e) => {
    if (!start) return;
    const wasDrag = moved;
    start = null;
    moved = false;
    el.classList.remove("dragging");
    shell?.dragEnd?.();
    if (!wasDrag && e.type === "pointerup") el.__petHooks.onPoke(e);
  };

  el.addEventListener("pointerup", end);
  el.addEventListener("pointercancel", end);
}
